### ISSUE TITLE
TypeError: Cannot call method 'get' of undefined

### ISSUE THREAD

**Issue by HLFH** [psychobunny/nodebb-plugin-blog-comments#23]
I got this issue when I want to run nodebb.

```bash
2014-12-12T00:43:31.824Z - error: TypeError: Cannot call method 'get' of undefined
    at Object.Comments.init (/var/www/nodebb/node_modules/nodebb-plugin-blog-comments/library.js:222:7)
    at /var/www/nodebb/src/plugins.js:489:23
    at /var/www/nodebb/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/var/www/nodebb/node_modules/async/lib/async.js:46:24)
    at Object.async.each (/var/www/nodebb/node_modules/async/lib/async.js:124:9)
    at Object.Plugins.fireHook (/var/www/nodebb/src/plugins.js:487:12)
    at Plugins.reloadRoutes (/var/www/nodebb/src/plugins.js:135:11)
    at /var/www/nodebb/node_modules/async/lib/async.js:656:23
    at fn (/var/www/nodebb/node_modules/async/lib/async.js:641:34)
TypeError: Cannot call method 'get' of undefined
    at Object.Comments.init (/var/www/nodebb/node_modules/nodebb-plugin-blog-comments/library.js:222:7)
    at /var/www/nodebb/src/plugins.js:489:23
    at /var/www/nodebb/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/var/www/nodebb/node_modules/async/lib/async.js:46:24)
    at Object.async.each (/var/www/nodebb/node_modules/async/lib/async.js:124:9)
    at Object.Plugins.fireHook (/var/www/nodebb/src/plugins.js:487:12)
    at Plugins.reloadRoutes (/var/www/nodebb/src/plugins.js:135:11)
    at /var/www/nodebb/node_modules/async/lib/async.js:656:23
    at fn (/var/www/nodebb/node_modules/async/lib/async.js:641:34)
2014-12-12T00:43:31.825Z - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
2014-12-12T00:43:31.826Z - info: [app] Database connection closed.

net.js:1236
    throw new Error('Not running');
          ^
Error: Not running
    at Server.close (net.js:1236:11)
    at shutdown (/var/www/nodebb/app.js:344:36)
    at process.<anonymous> (/var/www/nodebb/app.js:181:7)
    at process.emit (events.js:95:17)
    at process._fatalException (node.js:272:26)
```

**Comment by psychobunny** [comment]
I've just released v0.3.0 of this plugin:

* Fixed quite a few server crashes (especially when publishing)
* Compatible with NodeBB 0.6x+ and Ghost 0.5.10

Sorry for the super delay, I haven't had much chance outside of NodeBB development to dedicate to this plugin until now
