### ISSUE TITLE
Not working since I upgaded the nodebb to version v1.11.2

### ISSUE THREAD

**Issue by zozo6015** [psychobunny/nodebb-plugin-blog-comments#83]
When I try to add tie the blog post to the nodebb I get the following error on the nodebb.

    2019-03-02T13:26:58.836Z [4568/4981] - error: /comments/publish

    SyntaxError: Unexpected end of JSON input
        at JSON.parse (<anonymous>)
        at Comments.publishArticle (/var/www/z0z0/node_modules/nodebb-plugin-blog-comments/library.js:135:15)
        at Layer.handle [as handle_request] (/var/www/z0z0/node_modules/express/lib/router/layer.js:95:5)
        at next (/var/www/z0z0/node_modules/express/lib/router/route.js:137:13)
        at Route.dispatch (/var/www/z0z0/node_modules/express/lib/router/route.js:112:3)
        at Layer.handle [as handle_request] (/var/www/z0z0/node_modules/express/lib/router/layer.js:95:5)
        at /var/www/z0z0/node_modules/express/lib/router/index.js:281:22
        at Function.process_params (/var/www/z0z0/node_modules/express/lib/router/index.js:335:12)
        at next (/var/www/z0z0/node_modules/express/lib/router/index.js:275:10)
        at rewrite (/var/www/z0z0/src/controllers/home.js:33:10)

Is there anything I need to do to fix it? Note the comments on the same version of ghost was working before I updated the nodebb.

**Comment by psychobunny** [comment]
Hi, what version of the blog comments plugin are you running? I feel like this may have been fixed already and perhaps you are using an older version?

**Comment by zozo6015** [comment]
npm list | grep nodebb-plugin-blog-comments
├── nodebb-plugin-blog-comments@0.5.6

**Comment by zozo6015** [comment]
After upgrading ghost to the latest version everything works as expected.
