### ISSUE TITLE
Empty comment list in Ghost. Error in ghost.js

### ISSUE THREAD

**Issue by scaldov** [psychobunny/nodebb-plugin-blog-comments#88]
Uncaught TypeError: Cannot set property 'onclick' of null
    at XMLHttpRequest.XHR.onload (ghost.js:110)

var loadMore = document.getElementById('nodebb-load-more');
				loadMore.onclick = function() {
	

There is no such an element nodebb-load-more in post page, allthough it presents in comments.tpl

**Comment by scaldov** [comment]
Ghost version: 3.12.1
NodeBB v1.13.2.
all are up to date

**Comment by scaldov** [comment]
[2020-04-07 09:28:10] ERROR Error parsing filter

Error parsing filter

Error ID:
    1921d1a0-78b2-11ea-8189-95c9226f14b5

----------------------------------------

BadRequestError: Error parsing filter
    at new BadRequestError (/home/ghost/ghost/versions/3.12.1/node_modules/ghost-ignition/lib/errors/index.js:113:23)
    at Child.applyDefaultAndCustomFilters (/home/ghost/ghost/versions/3.12.1/core/server/models/plugins/filter.js:90:23)
    at Function.findPage (/home/ghost/ghost/versions/3.12.1/core/server/models/base/index.js:883:24)
    at Object.query (/home/ghost/ghost/versions/3.12.1/core/server/api/canary/posts-public.js:32:32)
    at Object.query (/home/ghost/ghost/versions/3.12.1/core/server/api/shared/pipeline.js:156:24)
    at Promise.resolve.then.then.then.then (/home/ghost/ghost/versions/3.12.1/core/server/api/shared/pipeline.js:241:35)
    at tryCatcher (/home/ghost/ghost/versions/3.12.1/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ghost/ghost/versions/3.12.1/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/ghost/ghost/versions/3.12.1/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/ghost/ghost/versions/3.12.1/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/ghost/ghost/versions/3.12.1/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/home/ghost/ghost/versions/3.12.1/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/ghost/ghost/versions/3.12.1/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/ghost/ghost/versions/3.12.1/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/ghost/ghost/versions/3.12.1/node_modules/bluebird/js/release/async.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:120:23)

Error: Query Error: unexpected character in filter at char 7
(tags:[]+id:-5e8b79166d7538
-------^
Expecting 'NULL', 'TRUE', 'FALSE', 'NUMBER', 'LITERAL', 'STRING', got 'RBRACKET'
    at Parser.parser.parseError (/home/ghost/ghost/versions/3.12.1/node_modules/@nexes/nql-lang/dist/parser.js:328:12)
    at Parser.parse (/home/ghost/ghost/versions/3.12.1/node_modules/@nexes/nql-lang/dist/parser.js:245:22)
    at Object.exports.parse (/home/ghost/ghost/versions/3.12.1/node_modules/@nexes/nql-lang/lib/nql.js:18:44)
    at Object.api.parse (/home/ghost/ghost/versions/3.12.1/node_modules/@nexes/nql/lib/nql.js:15:31)
    at Object.api.querySQL.qb [as querySQL] (/home/ghost/ghost/versions/3.12.1/node_modules/@nexes/nql/lib/nql.js:49:44)
    at Builder.query (/home/ghost/ghost/versions/3.12.1/core/server/models/plugins/filter.js:87:24)
    at Object.query (/home/ghost/ghost/versions/3.12.1/node_modules/bookshelf/lib/helpers.js:58:14)
    at Child.query (/home/ghost/ghost/versions/3.12.1/node_modules/bookshelf/lib/model.js:1332:22)
    at Child.applyDefaultAndCustomFilters (/home/ghost/ghost/versions/3.12.1/core/server/models/plugins/filter.js:80:22)
    at Function.findPage (/home/ghost/ghost/versions/3.12.1/core/server/models/base/index.js:883:24)
    at Object.query (/home/ghost/ghost/versions/3.12.1/core/server/api/canary/posts-public.js:32:32)
    at Object.query (/home/ghost/ghost/versions/3.12.1/core/server/api/shared/pipeline.js:156:24)
    at Promise.resolve.then.then.then.then (/home/ghost/ghost/versions/3.12.1/core/server/api/shared/pipeline.js:241:35)
    at tryCatcher (/home/ghost/ghost/versions/3.12.1/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ghost/ghost/versions/3.12.1/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/ghost/ghost/versions/3.12.1/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/ghost/ghost/versions/3.12.1/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/ghost/ghost/versions/3.12.1/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/home/ghost/ghost/versions/3.12.1/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/ghost/ghost/versions/3.12.1/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/ghost/ghost/versions/3.12.1/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/ghost/ghost/versions/3.12.1/node_modules/bluebird/js/release/async.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:120:23)

[2020-04-07 09:28:11] INFO "GET /blog/avatar/" 200 155ms
[2020-04-07 09:28:11] INFO "GET /blog/assets/css/app.css?v=b569912d60" 200 7ms
[2020-04-07 09:28:11] INFO "GET /blog/favicon.ico" 200 3ms

**Comment by scaldov** [comment]
script ghost.js:164 from post.hbs issues a request:
GET https://scyld.org/forum/comments/get/5e8b79166d7538094e0d74a0/0
I can see in the response all comments made, but they are not rendered in page.

The response is:

{
    "posts": [
        {
            "content": "<p dir=\"auto\"><img src=\"/forum/assets/uploads/files/1586199533196-scaldov-av.jpg\" alt=\"scaldov-av.jpg\" class=\"img-responsive img-markdown\" /><br />\nLOL</p>\n",
            "pid": 24,
            "tid": 5,
            "timestamp": 1586199542832,
            "toPid": "21",
            "uid": 1,
            "deleted": 0,
            "upvotes": 0,
            "downvotes": 0,
            "deleterUid": 0,
            "edited": 0,
            "votes": 0,
            "timestampISO": "2020-04-06T18:59:02.832Z",
            "editedISO": "",
            "index": 1,
            "parent": {
                "username": "scaldov"
            },
            "user": {
                "uid": 1,
                "username": "scaldov",
                "userslug": "scaldov",
                "reputation": 0,
                "postcount": 5,
                "topiccount": 1,
                "picture": null,
                "signature": "",
                "banned": 0,
                "banned:expire": 0,
                "status": "online",
                "lastonline": 1586263646925,
                "groupTitle": "[\"administrators\"]",
                "groupTitleArray": [
                    "administrators"
                ],
                "icon:text": "S",
                "icon:bgColor": "#009688",
                "lastonlineISO": "2020-04-07T12:47:26.925Z",
                "banned_until": 0,
                "banned_until_readable": "Not Banned",
                "selectedGroups": [],
                "custom_profile_info": []
            },
            "editor": null,
            "bookmarked": false,
            "upvoted": false,
            "downvoted": false,
            "replies": {
                "hasMore": false,
                "users": [],
                "text": "[[topic:one_reply_to_this_post]]",
                "count": 0
            },
            "selfPost": true
        },
        {
            "content": "<p dir=\"auto\"><a class=\"plugin-mentions-user plugin-mentions-a\" href=\"https://scyld.org/forum/uid/1\">@scaldov</a> said in <a href=\"/forum/post/22\">Avatar</a>:</p>\n<blockquote>\n<p dir=\"auto\"><a class=\"plugin-mentions-user plugin-mentions-a\" href=\"https://scyld.org/forum/uid/1\">@scaldov</a> LoL</p>\n</blockquote>\n<p dir=\"auto\">Жесть</p>\n",
            "pid": 23,
            "tid": 5,
            "timestamp": 1586198991970,
            "toPid": "22",
            "uid": 1,
            "deleted": 0,
            "upvotes": 0,
            "downvotes": 0,
            "deleterUid": 0,
            "edited": 0,
            "votes": 0,
            "timestampISO": "2020-04-06T18:49:51.970Z",
            "editedISO": "",
            "index": 2,
            "parent": {
                "username": "scaldov"
            },
            "user": {
                "uid": 1,
                "username": "scaldov",
                "userslug": "scaldov",
                "reputation": 0,
                "postcount": 5,
                "topiccount": 1,
                "picture": null,
                "signature": "",
                "banned": 0,
                "banned:expire": 0,
                "status": "online",
                "lastonline": 1586263646925,
                "groupTitle": "[\"administrators\"]",
                "groupTitleArray": [
                    "administrators"
                ],
                "icon:text": "S",
                "icon:bgColor": "#009688",
                "lastonlineISO": "2020-04-07T12:47:26.925Z",
                "banned_until": 0,
                "banned_until_readable": "Not Banned",
                "selectedGroups": [],
                "custom_profile_info": []
            },
            "editor": null,
            "bookmarked": false,
            "upvoted": false,
            "downvoted": false,
            "replies": {
                "hasMore": false,
                "users": [],
                "text": "[[topic:one_reply_to_this_post]]",
                "count": 0
            },
            "selfPost": true
        },
        {
            "content": "<p dir=\"auto\"><a class=\"plugin-mentions-user plugin-mentions-a\" href=\"https://scyld.org/forum/uid/1\">@scaldov</a> LoL</p>\n",
            "pid": 22,
            "tid": 5,
            "timestamp": 1586198930106,
            "toPid": "21",
            "uid": 1,
            "replies": {
                "hasMore": false,
                "users": [
                    {
                        "uid": 1,
                        "username": "scaldov",
                        "userslug": "scaldov",
                        "picture": null,
                        "icon:text": "S",
                        "icon:bgColor": "#009688",
                        "administrator": true
                    }
                ],
                "text": "[[topic:one_reply_to_this_post]]",
                "count": 1,
                "timestampISO": "2020-04-06T18:49:51.970Z"
            },
            "deleted": 0,
            "upvotes": 0,
            "downvotes": 0,
            "deleterUid": 0,
            "edited": 0,
            "votes": 0,
            "timestampISO": "2020-04-06T18:48:50.106Z",
            "editedISO": "",
            "index": 3,
            "parent": {
                "username": "scaldov"
            },
            "user": {
                "uid": 1,
                "username": "scaldov",
                "userslug": "scaldov",
                "reputation": 0,
                "postcount": 5,
                "topiccount": 1,
                "picture": null,
                "signature": "",
                "banned": 0,
                "banned:expire": 0,
                "status": "online",
                "lastonline": 1586263646925,
                "groupTitle": "[\"administrators\"]",
                "groupTitleArray": [
                    "administrators"
                ],
                "icon:text": "S",
                "icon:bgColor": "#009688",
                "lastonlineISO": "2020-04-07T12:47:26.925Z",
                "banned_until": 0,
                "banned_until_readable": "Not Banned",
                "selectedGroups": [],
                "custom_profile_info": []
            },
            "editor": null,
            "bookmarked": false,
            "upvoted": false,
            "downvoted": false,
            "selfPost": true
        },
        {
            "content": "<p dir=\"auto\">test comment</p>\n",
            "pid": 21,
            "tid": 5,
            "timestamp": 1586198892941,
            "uid": 1,
            "replies": {
                "hasMore": false,
                "users": [
                    {
                        "uid": 1,
                        "username": "scaldov",
                        "userslug": "scaldov",
                        "picture": null,
                        "icon:text": "S",
                        "icon:bgColor": "#009688",
                        "administrator": true
                    }
                ],
                "text": "[[topic:replies_to_this_post, 2]]",
                "count": 2,
                "timestampISO": "2020-04-06T18:48:50.106Z"
            },
            "deleted": 0,
            "upvotes": 0,
            "downvotes": 0,
            "deleterUid": 0,
            "edited": 0,
            "votes": 0,
            "timestampISO": "2020-04-06T18:48:12.941Z",
            "editedISO": "",
            "index": 4,
            "user": {
                "uid": 1,
                "username": "scaldov",
                "userslug": "scaldov",
                "reputation": 0,
                "postcount": 5,
                "topiccount": 1,
                "picture": null,
                "signature": "",
                "banned": 0,
                "banned:expire": 0,
                "status": "online",
                "lastonline": 1586263646925,
                "groupTitle": "[\"administrators\"]",
                "groupTitleArray": [
                    "administrators"
                ],
                "icon:text": "S",
                "icon:bgColor": "#009688",
                "lastonlineISO": "2020-04-07T12:47:26.925Z",
                "banned_until": 0,
                "banned_until_readable": "Not Banned",
                "selectedGroups": [],
                "custom_profile_info": []
            },
            "editor": null,
            "bookmarked": false,
            "upvoted": false,
            "downvoted": false,
            "selfPost": true
        }
    ],
    "postCount": 5,
    "user": {
        "uid": 1,
        "username": "scaldov",
        "userslug": "scaldov",
        "email": "scaldov@yandex.ru",
        "email:confirmed": 0,
        "joindate": 1586107026889,
        "lastonline": 1586263646925,
        "picture": null,
        "fullname": null,
        "location": null,
        "birthday": null,
        "website": null,
        "aboutme": null,
        "signature": null,
        "uploadedpicture": null,
        "profileviews": 0,
        "reputation": 0,
        "postcount": 5,
        "topiccount": 1,
        "lastposttime": 1586199542832,
        "banned": 0,
        "banned:expire": 0,
        "status": "online",
        "flags": null,
        "followerCount": 0,
        "followingCount": 0,
        "cover:url": null,
        "cover:position": null,
        "groupTitle": "[\"administrators\"]",
        "groupTitleArray": [
            "administrators"
        ],
        "icon:text": "S",
        "icon:bgColor": "#009688",
        "joindateISO": "2020-04-05T17:17:06.889Z",
        "lastonlineISO": "2020-04-07T12:47:26.925Z",
        "banned_until": 0,
        "banned_until_readable": "Not Banned"
    },
    "template": "\r\n\t\r\n\t\t<div class=\"topic-profile-pic user\">\r\n\t\t\t\r\n\t\t\t<img src=\"{user.picture}\" class=\"profile-image\" />\r\n\t\t\t\r\n\t\t\t<img src=\"https://1.gravatar.com/avatar/177d180983be7a2c95a4dbe7451abeba?s=95&d=&r=PG\" class=\"profile-image\" />\r\n\t\t\t\r\n\t\t</div>\r\n\t\t<form action=\"{relative_path}/comments/reply\" method=\"post\">\r\n\t\t\t<textarea id=\"nodebb-content\" class=\"form-control\" name=\"content\" placeholder=\"Join the conversation\" rows=\"3\"></textarea>\r\n\t\t\r\n\t\t\t<small>Signed in as <strong>{user.username}</strong>. <strong id=\"nodebb-error\"></strong></small>\r\n\t\t\t<button class=\"btn btn-primary\">Post a Reply</button>\r\n\t\t\t<input type=\"hidden\" name=\"_csrf\" value=\"{token}\" />\r\n\t\t\t<input type=\"hidden\" name=\"tid\" value=\"{tid}\" />\r\n\t\t\t<input type=\"hidden\" name=\"url\" value=\"{redirect_url}\" />\r\n\t\t</form>\r\n\t\t\r\n\t\t</form>\r\n\t\t<button class=\"btn btn-primary\" id=\"nodebb-register\">Register</button>\r\n\t\t<button class=\"btn btn-primary\" id=\"nodebb-login\">Login</button>\r\n\t\t<br />\r\n\t\t\r\n\t\r\n\r\n\t<ul id=\"nodebb-comments-list\">\r\n\t\t\r\n\t\t<li  class=\"nodebb-post-fadein\"   class=\"nodebb-post-fadein\"  >\r\n\t\t\t<div class=\"topic-item\">\r\n\t\t\t\t<div class=\"topic-body\">\r\n\t\t\t\t\t<div class=\"topic-profile-pic\">\r\n\t\t\t\t\t\t<a href=\"{relative_path}/user/{user.userslug}\">\r\n\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t<img src=\"{user.picture}\" alt=\"{user.username}\" class=\"profile-image\" title=\"{user.username}\">\r\n\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t<div class=\"profile-image\" style=\"background-color: {user.icon:bgColor}\" title=\"{user.username}\" alt=\"{user.username}\">{user.icon:text}</div>\r\n\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t</a>\r\n\t\t\t\t\t</div>\r\n\t\t\t\t\t<div class=\"topic-text\">\r\n\t\t\t\t\t\t<div class=\"post-content\" itemprop=\"text\"><small><strong>{user.username}</strong> commented {posts.timestamp}</small><br />{posts.content}</div>\r\n\t\t\t\t\t</div>\r\n\t\t\t\t</div>\r\n\t\t\t</div>\r\n\t\t</li>\r\n\t\t\r\n\t</ul>\r\n\t<br />\r\n\r\n\t\r\n\t\t<div class=\"topic-profile-pic user\">\r\n\t\t\t\r\n\t\t\t<img src=\"{user.picture}\" class=\"profile-image\" />\r\n\t\t\t\r\n\t\t\t<img src=\"http://1.gravatar.com/avatar/177d180983be7a2c95a4dbe7451abeba?s=95&d=&r=PG\" class=\"profile-image\" />\r\n\t\t\t\r\n\t\t</div>\r\n\t\t<form action=\"{relative_path}/comments/reply\" method=\"post\">\r\n\t\t\t<textarea id=\"nodebb-content\" class=\"form-control\" name=\"content\" placeholder=\"Join the conversation\" rows=\"3\"></textarea>\r\n\t\t\r\n\t\t\t<small>Signed in as <strong>{user.username}</strong>. <strong id=\"nodebb-error\"></strong></small>\r\n\t\t\t<button class=\"btn btn-primary\">Post a Reply</button>\r\n\t\t\t<input type=\"hidden\" name=\"_csrf\" value=\"{token}\" />\r\n\t\t\t<input type=\"hidden\" name=\"tid\" value=\"{tid}\" />\r\n\t\t\t<input type=\"hidden\" name=\"url\" value=\"{redirect_url}\" />\r\n\t\t</form>\r\n\t\t\r\n\t\t</form>\r\n\t\t<button class=\"btn btn-primary\" id=\"nodebb-register\">Register</button>\r\n\t\t<button class=\"btn btn-primary\" id=\"nodebb-login\">Login</button>\r\n\t\t<br />\r\n\t\t\r\n\t\r\n\r\n\t<small class=\"nodebb-copyright\">Powered by <a href=\"http://nodebb.org\" target=\"_blank\">NodeBB</a> &bull; <a href=\"{relative_path}/topic/{tid}\">View original thread</a></small>\r\n\t<button class=\"btn btn-primary\" style=\"display: none\" id=\"nodebb-load-more\">Load more comments...</button>\r\n\r\n\tCommenting has been disabled.\r\n\t\r\n\t<form action=\"{relative_path}/comments/publish\" method=\"post\">\r\n\t\t<button class=\"btn btn-primary\">Publish this article to NodeBB</button>\r\n\t\t<input type=\"hidden\" name=\"markdown\" id=\"nodebb-content-markdown\" />\r\n\t\t<input type=\"hidden\" name=\"title\" id=\"nodebb-content-title\" />\r\n\t\t<input type=\"hidden\" name=\"cid\" id=\"nodebb-content-cid\" />\r\n\t\t<input type=\"hidden\" name=\"tags\" id=\"nodebb-content-tags\" />\r\n\t\t<input type=\"hidden\" name=\"id\" value=\"{article_id}\" />\r\n\t\t<input type=\"hidden\" name=\"url\" value=\"{redirect_url}\" />\r\n\t\t<input type=\"hidden\" name=\"_csrf\" value=\"{token}\" />\r\n\t</form>\r\n\t\r\n\r\n",
    "token": "wGPBkTZl-N4SNx7kRqr1P24ttzecB85y9m-w",
    "isAdmin": true,
    "isLoggedIn": true,
    "tid": 5,
    "category": {
        "bgColor": "#e95c5a",
        "cid": 4,
        "class": "col-md-3 col-xs-6",
        "color": "#fff",
        "description": "Got a question? Ask away!",
        "descriptionParsed": "<p>Got a question? Ask away!</p>\n",
        "disabled": 0,
        "icon": "fa-question",
        "imageClass": "cover",
        "isSection": 0,
        "link": "",
        "name": "Comments &amp; Feedback",
        "numRecentReplies": 1,
        "order": 3,
        "parentCid": 0,
        "post_count": 5,
        "slug": "4/comments-feedback",
        "topic_count": 1,
        "totalPostCount": 5,
        "totalTopicCount": 1
    },
    "atBottom": false,
    "atTop": true
}
